#!/usr/bin/env python3
r"""THE ANGELIC HIERARCHY — the second column of the Gnostic Lineage, standing beside the
Monad→Sophia emanation and ABOVE the Sophia→Demiurge divide. Drawn from 3 Enoch (Sefer
Hekhalot, the Hekhalot angelology), with the archangels and Watchers of 1 Enoch and the
seven heavens of 2 Enoch. The order is the text's own ascending precedence — each rank
bows to the one above it — and the famous escalating scale (parasangs; a wing as wide as
the world; a cherub as big as the world; Chayyliel who swallows the earth in one mouthful;
Metatron enlarged to the size of the world) is preserved in each `place`/`nature` line.

Every entity carries `col: "angelic"` so the renderer draws it as a distinct column; tiers
0–6 keep it above the divide (which is keyed to the emanation's first_deficiency at tier 7).
Each is `side: "fullness"`. Members hold the individually-named angels with their sizes,
ranks, and stated name-meanings, and each name flows to the Hebrew letter-by-letter study.
"""

# ranks, greatest → least (tier 0 = the viceroy, tier 6 = the hosts)
ANGELIC = [
    {"id": "ang_metatron", "name": "Metatron", "aka": "the Lesser YHWH · Prince of the Presence · the Youth (Na'ar)",
     "tier": 0, "side": "fullness", "parent": None, "col": "angelic",
     "definition": "Enoch son of Jared, taken up and transformed into the greatest of the angels — viceroy over all the host of heaven, prince over all the princes save the eight great princes called YHWH, and the Lesser YHWH in whom the Name dwells (3 Enoch 10, 12, 48C). He stands and serves before the Throne of Glory, and every prince passes before him to speak to God.",
     "appearance": "Enlarged to the size of the length and breadth of the world, with 72 wings — each wing as wide as the whole world — and 365 eyes, each as great as the great luminary; his stature and his throne of fire seventy thousand parasangs, his crown five hundred by five hundred parasangs (3 Enoch 9, 48C).",
     "nature": "The 'Youth' (Na'ar), least and youngest made greatest; bearer of seventy names for the seventy tongues, and of the crown on which the letters by which heaven and earth were sealed are graven. 'My name is in him' (Exodus 23:21).",
     "search": ["metatron", "the lesser yhwh", "prince of the presence", "enoch"],
     "members": [
        {"name": "Yehoel", "roster": "The names of Metatron", "place": "3 Enoch 48D",
         "aka": "YHWH-El", "definition": "The first of the seventy names of Metatron — Yeho-El, 'YHWH is God' — one of the names given him in the treasuries of the Name.",
         "appearance": "A name of power graven among Metatron's seventy names.", "nature": "The Name borne by the viceroy.",
         "search": ["yehoel", "metatron"]},
        {"name": "The Youth (Na'ar)", "roster": "The names of Metatron", "place": "3 Enoch 3–4",
         "aka": "Na'ar", "definition": "The title by which the King calls Metatron — 'Youth' — because he is small and young among the angels in days, being Enoch who ascended.",
         "appearance": "Called Youth though he towers as the world.", "nature": "The least made the greatest.",
         "search": ["youth", "naar", "metatron"]},
        {"name": "Segansakkiel", "roster": "The names of Metatron", "place": "Prince of Wisdom · 3 Enoch 48D",
         "aka": "Sagnesakiel · Prince of Wisdom", "definition": "Prince of Wisdom, in whose hand all the treasuries of wisdom are committed — reckoned among Metatron's names.",
         "appearance": "Keeper of the treasuries of wisdom.", "nature": "Wisdom given into a hand.",
         "search": ["segansakkiel", "sagnesakiel", "prince of wisdom"]},
     ]},

    {"id": "ang_council", "name": "The Irin & Qaddishin", "aka": "the Watchers & Holy Ones · the four great princes",
     "tier": 1, "side": "fullness", "parent": "ang_metatron", "col": "angelic",
     "definition": "Four great princes — two Watchers (Irin) and two Holy Ones (Qaddishin) — greater than all the children of heaven; the Holy One does nothing in His world without first taking counsel of them (3 Enoch 28, after Daniel 4:17). Above even the great princes.",
     "appearance": "Each equal to all the rest together; from each go forth sparks and lightnings, surrounded by tents of brilliance so that even the Seraphim and Chayyoth cannot behold them (3 Enoch 29).",
     "nature": "God's own council. Called Irin and Qaddishin because they sanctify (qaddesh) body and spirit with lashes of fire on the day of judgement.",
     "search": ["irin", "qaddishin", "watchers", "holy ones"],
     "members": [
        {"name": "The two Irin (Watchers)", "roster": "The four princes of the council", "place": "3 Enoch 28:5",
         "aka": "the Watchers", "definition": "The two 'Watchers' of the supreme four — the wakeful princes of God's decree.",
         "appearance": "Surrounded by tents of brilliance.", "nature": "They watch and decree.",
         "search": ["irin", "watchers"]},
        {"name": "The two Qaddishin (Holy Ones)", "roster": "The four princes of the council", "place": "3 Enoch 28:5",
         "aka": "the Holy Ones", "definition": "The two 'Holy Ones' of the supreme four — who sanctify with fire.",
         "appearance": "Sparks and lightnings go forth from them.", "nature": "They sanctify body and spirit.",
         "search": ["qaddishin", "holy ones"]},
     ]},

    {"id": "ang_chief", "name": "The Great Chief Princes", "aka": "over the Seraphim, Ophannim, Kerubim, Chayyoth & the wheels",
     "tier": 2, "side": "fullness", "parent": "ang_council", "col": "angelic",
     "definition": "The mighty princes set each over one order of the living chariot, in the text's own 'above these there is one prince' ascent — from Rikbiel over the wheels up to Radweriel, out of whose every word an angel is created (3 Enoch 19–27), with the two scribe-princes Sopheriel who write the books of the living and the dead.",
     "appearance": "Each as high as the seven heavens, their bodies full of eyes; Seraphiel's head-sapphire as great as the whole universe (3 Enoch 26).",
     "nature": "The keepers of the four living creatures of the Merkaba and their fire.",
     "search": ["seraphiel", "kerubiel", "ophphanniel", "chayyliel", "rikbiel", "radweriel"],
     "members": [
        {"name": "Radweriel", "roster": "Above the Seraphim", "place": "keeper of the books · 3 Enoch 27",
         "aka": "H'", "definition": "Exalted above all the princes, keeper of the treasuries of the books; he brings the Case of Writings before God. Called Radweriel because out of every word that goes forth from his mouth an angel is created.",
         "appearance": "Wondrous beyond all the servants.", "nature": "His speech is angel-making.",
         "search": ["radweriel"]},
        {"name": "Seraphiel", "roster": "Prince over the Seraphim", "place": "height as the seven heavens · 3 Enoch 26",
         "aka": "the Prince of Peace", "definition": "Appointed over the Seraphim; a chief, leader and swift scribe. His crown is named 'the Prince of Peace.' The Seraphim are so called because they burn (saraph) the tablets of Satan.",
         "appearance": "His height as the seven heavens; his body like an eagle's; the sapphire on his head as great as the universe; his crown a journey of 502 years.",
         "nature": "The burning ones' prince.", "search": ["seraphiel", "seraphim"]},
        {"name": "'Ophphanniel", "roster": "Prince over the Ophannim", "place": "16 faces · 8466 eyes · 3 Enoch 25",
         "aka": "H'", "definition": "The great prince appointed over the 'Ophannim (the wheels full of eyes).",
         "appearance": "Sixteen faces, four each side, a hundred wings each side, and 8466 eyes for the days of the year; height a journey of 2500 years.",
         "nature": "Over the wheels of the chariot.", "search": ["ophphanniel", "ophannim"]},
        {"name": "Kerubiel", "roster": "Prince over the Kerubim", "place": "height/breadth/thickness of seven heavens · 3 Enoch 22A",
         "aka": "H'", "definition": "Appointed over the chariot of the Kerubim; the two princes of the Merkaba stand with him.",
         "appearance": "Stature, breadth and thickness each as the seven heavens; his body full of eyes; his wings cover his whole height.",
         "nature": "Over the cherubim of the chariot.", "search": ["kerubiel", "kerubim", "cherubim"]},
        {"name": "Chayyliel", "roster": "Prince over the Holy Chayyoth", "place": "swallows the earth in one mouthful · 3 Enoch 20",
         "aka": "H'", "definition": "The great and mighty prince appointed over the Holy Chayyoth (living creatures), whom he smites with lashes of fire.",
         "appearance": "A prince able to swallow up the whole earth in one moment, at a single mouthful.",
         "nature": "Over the living creatures.", "search": ["chayyliel", "chayyoth", "living creatures"]},
        {"name": "Rikbiel", "roster": "Prince over the wheels of the Merkaba", "place": "3 Enoch 19",
         "aka": "H'", "definition": "Set above the three chariot-princes; appointed over the wheels (rekeb) of the Merkaba, like whom there is none among the princes.",
         "appearance": "Chief of the chariot-wheels.", "nature": "The chariot moves at his charge.",
         "search": ["rikbiel"]},
        {"name": "Sopheriel who kills", "roster": "The two scribe-princes", "place": "books of the dead · 3 Enoch 18:24",
         "aka": "Sopheriel the Killer", "definition": "One of the two great scribe-princes; appointed over the books of the dead — he writes a man into the book of the dead.",
         "appearance": "Height as seven heavens; body full of eyes; wings as the days of the year; his burning scroll and style 3000 myriads of parasangs, each letter he writes 365 parasangs.",
         "nature": "The scribe of death.", "search": ["sopheriel"]},
        {"name": "Sopheriel who makes alive", "roster": "The two scribe-princes", "place": "books of the living · 3 Enoch 18:24",
         "aka": "Sopheriel the Lifegiver", "definition": "The second great scribe-prince; appointed over the books of the living — he writes a man into the book of life, by the authority of MAQOM.",
         "appearance": "As his fellow: seven-heaven height, letters of 365 parasangs.",
         "nature": "The scribe of life.", "search": ["sopheriel"]},
     ]},

    {"id": "ang_ladder", "name": "The Crown-Removal Ladder", "aka": "the princes who bow, each to the one above",
     "tier": 3, "side": "fullness", "parent": "ang_chief", "col": "angelic",
     "definition": "A descending file of princes, each of whom 'removes the crown of glory from his head and falls on his face' before the prince above him (3 Enoch 18) — the very picture of the hierarchy: every rank bows to the greater. Listed here greatest first.",
     "appearance": "Crowned princes prostrate in order, the least casting down his crown before the next.",
     "nature": "The order of homage — each honours the one set over him.",
     "search": ["anaphiel", "azbuga", "tagas", "zehanpuryu"],
     "members": [
        {"name": "'Azbuga", "roster": "The crown-ladder (greatest first)", "place": "girds the righteous · 3 Enoch 18:22",
         "aka": "H'", "definition": "Just below the two Sopheriel; in the age to come he will gird the righteous with garments of life.",
         "appearance": "A prince before the scribes.", "nature": "He robes the just.", "search": ["azbuga"]},
        {"name": "Zehanpuryu", "roster": "The crown-ladder (greatest first)", "place": "rebukes the fiery river · 3 Enoch 18:21",
         "aka": "H'", "definition": "He rebukes the fiery river and pushes it back.", "appearance": "Master of the river of fire.",
         "nature": "He restrains the flame.", "search": ["zehanpuryu"]},
        {"name": "Shoqed Chozi", "roster": "The crown-ladder (greatest first)", "place": "weighs merits · 3 Enoch 18:20",
         "aka": "", "definition": "He weighs all the merits of man in a balance.", "appearance": "Holder of the scales.",
         "nature": "The weigher of deeds.", "search": ["shoqed chozi", "shoqed"]},
        {"name": "Sother 'Ashiel", "roster": "The crown-ladder (greatest first)", "place": "height 7000 myriad parasangs · 3 Enoch 18:19",
         "aka": "H'", "definition": "Appointed over the four heads of the fiery river; its seals are entrusted to him.",
         "appearance": "His height seven thousand myriads of parasangs.", "nature": "Keeper of the river's seals.",
         "search": ["sother ashiel", "sother"]},
        {"name": "'Anaphiel", "roster": "The crown-ladder (greatest first)", "place": "keeper of the keys · 3 Enoch 18:18",
         "aka": "H'", "definition": "The prince who keeps the keys of the heavenly Halls; named because the bough (anaph) of his honour overshadows all the chambers of 'Araboth. He it is who bears Enoch aloft on a fiery chariot (3 Enoch 6).",
         "appearance": "His majesty a spreading bough over all the highest heaven.", "nature": "Keeper of the keys.",
         "search": ["anaphiel"]},
        {"name": "Zakzakiel", "roster": "The crown-ladder (greatest first)", "place": "writes Israel's merits · 3 Enoch 18:17",
         "aka": "H'", "definition": "Appointed to write down the merits of Israel upon the Throne of Glory.", "appearance": "Scribe at the Throne.",
         "nature": "Recorder of merit.", "search": ["zakzakiel"]},
        {"name": "Gallisur", "roster": "The crown-ladder (greatest first)", "place": "reveals the Law · 3 Enoch 18:16",
         "aka": "H' · Raziel", "definition": "He reveals all the secrets of the Torah.", "appearance": "Unveiler of the Law.",
         "nature": "Revealer of secrets.", "search": ["gallisur", "raziel"]},
        {"name": "'Ashruylu", "roster": "The crown-ladder (greatest first)", "place": "presides in the sessions · 3 Enoch 18:15",
         "aka": "H'", "definition": "He presides in all the sessions of the children of heaven.", "appearance": "Chair of the heavenly councils.",
         "nature": "President of the assembly.", "search": ["ashruylu"]},
        {"name": "'Araphiel, Geburatiel, Zazriel, Sasnigiel", "roster": "The crown-ladder (greatest first)", "place": "3 Enoch 18:11–14",
         "aka": "the titled princes", "definition": "Four great princes of the ladder named by their titles in order — 'Araphiel, Geburatiel (of might), Zazriel, Sasnigiel — each bowing to the one above.",
         "appearance": "Crowned princes in file.", "nature": "Ranks of the descending homage.",
         "search": ["araphiel", "geburatiel", "zazriel", "sasnigiel"]},
        {"name": "Na'aririel, Atrugiel, Tutresiel", "roster": "The crown-ladder (greatest first)", "place": "3 Enoch 18:8–10",
         "aka": "", "definition": "Three princes of the lower ladder, named in their turn.", "appearance": "Crowned princes in file.",
         "nature": "Ranks of homage.", "search": ["naaririel", "atrugiel", "tutresiel"]},
        {"name": "Hamon", "roster": "The crown-ladder (greatest first)", "place": "makes heaven tremble · 3 Enoch 18:7",
         "aka": "the fearful", "definition": "The fearful prince who makes all the children of heaven tremble at the hour of the Thrice-Holy — named from hamon, 'tumult' (Isaiah 33:3).",
         "appearance": "At his voice the host quakes.", "nature": "The trembling of the Sanctus.", "search": ["hamon"]},
        {"name": "Barattiel", "roster": "The crown-ladder (greatest first)", "place": "of three fingers · 3 Enoch 18:6",
         "aka": "", "definition": "The great prince who bears up the height of 'Araboth upon three fingers.", "appearance": "Three fingers upholding the highest heaven.",
         "nature": "Pillar of Araboth.", "search": ["barattiel"]},
        {"name": "Tag'as", "roster": "The crown-ladder (greatest first)", "place": "head of the song · 3 Enoch 18:5",
         "aka": "", "definition": "Great and honoured with song and praise, at the head of all the children of heaven — before whom the four princes of the Camps of Shekina bow.",
         "appearance": "Leader of the heavenly song.", "nature": "Master of praise.", "search": ["tagas"]},
     ]},

    {"id": "ang_realms", "name": "The Camps, Halls & Kingdoms", "aka": "the rungs of homage — camps, hall-keepers, the 72 princes",
     "tier": 4, "side": "fullness", "parent": "ang_ladder", "col": "angelic",
     "definition": "The lower rungs of the ladder (3 Enoch 17–18, 30): the four great princes over the Camps of the Shekina; the door-keepers of the seven Halls, each bowing to the next-higher Hall; the seventy-two Princes of the Kingdoms for the seventy-two tongues; and the Prince of the World who pleads for the world before God.",
     "appearance": "Crowned princes riding royal horses with sceptres; door-keepers ranged from the seventh Hall down to the first.",
     "nature": "The governance of the nations and the guard of the Halls.",
     "search": ["prince of the world", "princes of kingdoms", "camps of shekina"],
     "members": [
        {"name": "The four princes of the Camps of Shekina", "roster": "The rungs below the ladder", "place": "3 Enoch 18:4",
         "aka": "", "definition": "Four great princes set over the four camps of the Shekina, before whom the door-keepers of the seventh Hall bow.",
         "appearance": "Guardians of the four camps.", "nature": "The Shekina's own guard.", "search": ["camps of shekina", "shekina"]},
        {"name": "The door-keepers of the seven Halls", "roster": "The rungs below the ladder", "place": "3 Enoch 18:3",
         "aka": "", "definition": "The keepers of the seven Halls (Hekhalot); those of each Hall remove their crowns before those of the next-higher Hall, up to the Four Camps.",
         "appearance": "Keepers ranged from the first Hall to the seventh.", "nature": "The guard of the ascent.", "search": ["door keepers", "seven halls", "hekhalot"]},
        {"name": "The seventy-two Princes of Kingdoms", "roster": "The rungs below the ladder", "place": "for the 72 tongues · 3 Enoch 17:8; 30:2",
         "aka": "", "definition": "Seventy-two princes set over the seventy-two kingdoms and tongues of the world — crowned, on royal horses, with royal sceptres — before whom the prince of the seventh heaven bows.",
         "appearance": "Kings crowned and sceptred.", "nature": "The angelic governors of the nations.", "search": ["princes of kingdoms", "seventy two princes"]},
        {"name": "The Prince of the World", "roster": "The rungs below the ladder", "place": "Sar ha-Olam · 3 Enoch 30:2; 38:3",
         "aka": "Sar ha-Olam", "definition": "The prince who pleads in the world's favour before the Holy One each day when the book is opened, and who quiets the trembling heavenly bodies — 'Be ye quiet in your place!'",
         "appearance": "Advocate before the Throne.", "nature": "Steward and pleader of the created world.", "search": ["prince of the world", "sar ha-olam"]},
     ]},

    {"id": "ang_heavens", "name": "The Seven Princes of the Heavens", "aka": "Mikael, Gabriel & the archangels",
     "tier": 5, "side": "fullness", "parent": "ang_realms", "col": "angelic",
     "definition": "Seven princes, one over each of the seven heavens, each with hundreds of thousands of myriads of ministering angels (3 Enoch 17); Mikael the prince of Israel is highest, in 'Araboth. Joined here by the seven archangels who stand before the Lord in 1 Enoch — Michael, Gabriel, Raphael, Uriel, Raguel, Saraqael, Remiel.",
     "appearance": "Each attended by 496,000 myriads of ministering angels.",
     "nature": "The wardens of the seven heavens and the presence.",
     "search": ["michael", "gabriel", "raphael", "uriel", "raguel", "saraqael", "remiel"],
     "members": [
        {"name": "Mikael", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "7th heaven · 'Araboth · Prince of Israel",
         "aka": "Michael", "definition": "Prince of the seventh heaven and Prince of Israel (3 Enoch 17:3; 44:10); first of the archangels who stand before the Lord (1 Enoch).",
         "appearance": "Highest of the heaven-princes.", "nature": "Guardian prince of Israel.", "search": ["michael", "mikael"]},
        {"name": "Gabriel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "6th heaven · Makon · angel of the fire",
         "aka": "", "definition": "Prince of the sixth heaven and angel set over the fire (3 Enoch 14:4; 17:3); the archangel of the powers (1 Enoch).",
         "appearance": "Prince over fire.", "nature": "The might of God.", "search": ["gabriel"]},
        {"name": "Shatqiel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "5th heaven · Ma'on",
         "aka": "Shataqiel", "definition": "Prince of the fifth heaven.", "appearance": "Warden of Ma'on.",
         "nature": "Prince of the fifth height.", "search": ["shatqiel", "shataqiel"]},
        {"name": "Shahaqiel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "4th heaven · Zebul",
         "aka": "Shachaqiel", "definition": "Prince of the fourth heaven.", "appearance": "Warden of Zebul.",
         "nature": "Prince of the fourth height.", "search": ["shahaqiel", "shachaqiel"]},
        {"name": "Baradiel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "3rd heaven · Shehaqim · (also hail)",
         "aka": "Badariel", "definition": "Prince of the third heaven (and, among the world-rulers, over the hail).",
         "appearance": "Warden of Shehaqim.", "nature": "Prince of the third height.", "search": ["baradiel", "badariel"]},
        {"name": "Barakiel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "2nd heaven · Merom Raqia · (also lightnings)",
         "aka": "Bakariel", "definition": "Prince of the second heaven (and over the lightnings).",
         "appearance": "Warden of the second raqia.", "nature": "Prince of the second height.", "search": ["barakiel", "baraqiel"]},
        {"name": "Pazriel", "roster": "The seven heaven-princes (3 Enoch 17)", "place": "1st heaven · Wilon · Shamayim",
         "aka": "Pachriel", "definition": "Prince of the first heaven (the veil, Wilon).", "appearance": "Warden of the first heaven.",
         "nature": "Prince of the lowest height.", "search": ["pazriel", "pachriel"]},
        {"name": "Raphael, Uriel, Raguel, Saraqael, Remiel", "roster": "The archangels of 1 Enoch", "place": "1 Enoch 20",
         "aka": "the holy angels who watch", "definition": "The remaining archangels who stand before the Lord — Raphael over the spirits of men and healing, Uriel over the world and Tartarus, Raguel who takes vengeance on the world of luminaries, Saraqael over the spirits that sin, Remiel over those who rise (1 Enoch 20).",
         "appearance": "Holy watchers before the glory.", "nature": "The seven who present the prayers of the saints.",
         "search": ["raphael", "uriel", "raguel", "saraqael", "remiel"]},
     ]},

    {"id": "ang_hosts", "name": "The Luminary Princes, the Living Orders & the Fallen", "aka": "sun, moon, stars, the Chayyoth, and the Watchers who fell",
     "tier": 6, "side": "fullness", "parent": "ang_heavens", "col": "angelic",
     "definition": "The lowest ranks of the exalted host: the princes of the luminaries (sun, moon, stars, planets), the eighteen rulers of the natural world, and the four living orders that bear and surround the Throne — the Chayyoth, Kerubim, Ophannim and Seraphim — each as vast as the world. Set apart beneath them, the Watchers who fell and the accusers.",
     "appearance": "Each living creature as the space of the whole world, each wing like the roof of the universe; the moon-prince moving the moon 354,000 parasangs a night.",
     "nature": "The engines of day and night, and the four faces of the chariot — with the fallen shown below, apart.",
     "search": ["galgalliel", "chayyoth", "seraphim", "ophannim", "kerubim", "azazel", "sammael"],
     "members": [
        {"name": "Galgalliel", "roster": "The luminary princes (3 Enoch 14, 17)", "place": "the globe of the sun",
         "aka": "", "definition": "Prince over the galgal (globe) of the sun, with ninety-six angels.", "appearance": "Driver of the solar wheel.",
         "nature": "Over the sun.", "search": ["galgalliel"]},
        {"name": "'Ophanniel (of the moon)", "roster": "The luminary princes (3 Enoch 14, 17)", "place": "moves the moon 354,000 parasangs a night",
         "aka": "", "definition": "Prince over the globe of the moon, with eighty-eight angels, moving the moon 354,000 parasangs every night (distinct from the great 'Ophphanniel over the wheels).",
         "appearance": "Driver of the lunar globe.", "nature": "Over the moon.", "search": ["ophanniel", "moon"]},
        {"name": "Rahatiel", "roster": "The luminary princes (3 Enoch 14, 17)", "place": "the constellations · runs the stars 339,000 parasangs",
         "aka": "", "definition": "Prince over the constellations, with seventy-two angels; named because he makes the stars run (marhit) in their courses 339,000 parasangs a night.",
         "appearance": "Herald of the running stars.", "nature": "Over the constellations.", "search": ["rahatiel"]},
        {"name": "Kokbiel", "roster": "The luminary princes (3 Enoch 14, 17)", "place": "all the planets · 365,000 myriad angels",
         "aka": "", "definition": "Prince over all the planets, with 365,000 myriads of ministering angels.", "appearance": "Marshal of the planets.",
         "nature": "Over the planets (kokhav).", "search": ["kokbiel"]},
        {"name": "The eighteen rulers of the world", "roster": "The nature-princes (3 Enoch 14:3–4)", "place": "wind, hail, lightning, snow, rain, thunder, day & night",
         "aka": "Baradiel · Ruchiel · Baraqiel · Za'amiel · Ziqiel · Zi'iel · Za'aphiel · Ra'amiel · Ra'ashiel · Shalgiel · Matariel · Shimshiel · Lailiel …",
         "definition": "The eighteen princes set over the forces of nature — Ruchiel (wind), Baradiel (hail), Baraqiel (lightning), Ra'amiel (thunder), Ra'ashiel (earthquake), Shalgiel (snow), Matariel (rain), Shimshiel (day), Lailiel (night), and the rest — all of whom trembled before Metatron when he was crowned (3 Enoch 14).",
         "appearance": "The storm-angels of the sky.", "nature": "The governance of weather and season.",
         "search": ["ruchiel", "baraqiel", "matariel", "shalgiel", "lailiel", "shimshiel"]},
        {"name": "The Holy Chayyoth", "roster": "The four living orders", "place": "each as the whole world · 3 Enoch 21",
         "aka": "living creatures", "definition": "The four Living Creatures that bear the Throne — four faces and four wings each; each Chayya as the space of the whole world, each wing like the roof of the universe, with 2000 crowns on each head.",
         "appearance": "World-wide living creatures beneath the Throne.", "nature": "Bearers of the chariot.", "search": ["chayyoth", "living creatures"]},
        {"name": "The Kerubim", "roster": "The four living orders", "place": "one in each quarter · 3 Enoch 22A",
         "aka": "cherubim", "definition": "The cherubim on whom the Shekina rested; one set toward each quarter of the world, full of eyes and wings.",
         "appearance": "Eyed and winged, upholding the presence.", "nature": "Throne-bearers of glory.", "search": ["kerubim", "cherubim"]},
        {"name": "The Ophannim", "roster": "The four living orders", "place": "wheels full of eyes · 3 Enoch 25",
         "aka": "the wheels", "definition": "The 'wheels within wheels' full of eyes, set with seventy-two sapphire stones on each side.",
         "appearance": "Wheels of eyes.", "nature": "The turning of the chariot.", "search": ["ophannim", "wheels"]},
        {"name": "The Seraphim", "roster": "The four living orders", "place": "height as the seven heavens · 3 Enoch 26",
         "aka": "the burning ones", "definition": "The four burning ones, six wings and four faces each, whose height answers to the seven heavens and whose wings measure all Raqia; they burn (saraph) the tablets of Satan.",
         "appearance": "Six-winged flames as tall as the heavens.", "nature": "The burning worship before the Throne.", "search": ["seraphim"]},
        {"name": "The Watchers who fell — 'Uzza, 'Azza, 'Azzael", "roster": "The fallen (shown apart, below)", "place": "3 Enoch 4:6; 5:9",
         "aka": "Semjaza · Azazel", "definition": "Three ministering angels who accused Enoch's ascent and afterward taught sorceries to the generation of Enosh — the Watchers Semjaza and Azazel of 1 Enoch, who fell for the daughters of men and were bound.",
         "appearance": "Angels cast down from the height.", "nature": "The fall of the Watchers — free will, not programmed.", "search": ["azazel", "uzza", "azza", "semjaza", "watchers"]},
        {"name": "Sammael & Dubbiel — the accusers", "roster": "The fallen (shown apart, below)", "place": "3 Enoch 14:2; 26:12",
         "aka": "the Prince of Accusers · Prince of Rome / Prince of Persia", "definition": "Sammael, prince of the accusers, greater than all the princes of kingdoms, who with Satan writes the iniquities of Israel; and Dubbiel, prince of Persia, who sits with them.",
         "appearance": "Accusers at the opened book.", "nature": "The adversary among the princes.", "search": ["sammael", "dubbiel", "satan"]},
     ]},
]
