# -*- coding: utf-8 -*-
"""Hebrew names of the books (for the chapter/book-name study). OT names are the
traditional Hebrew titles; NT names are the common modern-Hebrew renderings."""

BOOK_HEBREW = {
    # ---- Torah / OT (traditional Hebrew titles) ----
    "Genesis": ("בְּרֵאשִׁית", "Bereshit", "In the beginning"),
    "Exodus": ("שְׁמוֹת", "Shemot", "Names"),
    "Leviticus": ("וַיִּקְרָא", "Vayikra", "And He called"),
    "Numbers": ("בְּמִדְבַּר", "Bamidbar", "In the wilderness"),
    "Deuteronomy": ("דְּבָרִים", "Devarim", "Words"),
    "Joshua": ("יְהוֹשֻׁעַ", "Yehoshua", "YHWH is salvation"),
    "Judges": ("שׁוֹפְטִים", "Shoftim", "Judges"),
    "Ruth": ("רוּת", "Rut", "Ruth (friendship)"),
    "1 Samuel": ("שְׁמוּאֵל", "Shemuel", "Heard by God"),
    "2 Samuel": ("שְׁמוּאֵל", "Shemuel", "Heard by God"),
    "1 Kings": ("מְלָכִים", "Melakhim", "Kings"),
    "2 Kings": ("מְלָכִים", "Melakhim", "Kings"),
    "1 Chronicles": ("דִבְרֵי הַיָּמִים", "Divrei HaYamim", "Words/events of the days"),
    "2 Chronicles": ("דִבְרֵי הַיָּמִים", "Divrei HaYamim", "Words/events of the days"),
    "Ezra": ("עֶזְרָא", "Ezra", "Help"),
    "Nehemiah": ("נְחֶמְיָה", "Nechemyah", "YHWH comforts"),
    "Esther": ("אֶסְתֵּר", "Ester", "Esther (star/hidden)"),
    "Job": ("אִיּוֹב", "Iyov", "Job (persecuted)"),
    "Psalms": ("תְּהִלִּים", "Tehillim", "Praises"),
    "Proverbs": ("מִשְׁלֵי", "Mishlei", "Proverbs of"),
    "Ecclesiastes": ("קֹהֶלֶת", "Qohelet", "Assembler / Preacher"),
    "Song of Solomon": ("שִׁיר הַשִּׁירִים", "Shir HaShirim", "Song of songs"),
    "Isaiah": ("יְשַׁעְיָהוּ", "Yeshayahu", "YHWH is salvation"),
    "Jeremiah": ("יִרְמְיָהוּ", "Yirmeyahu", "YHWH will exalt"),
    "Lamentations": ("אֵיכָה", "Eikhah", "How! (lament)"),
    "Ezekiel": ("יְחֶזְקֵאל", "Yechezqel", "God strengthens"),
    "Daniel": ("דָּנִיֵּאל", "Daniel", "God is my judge"),
    "Hosea": ("הוֹשֵׁעַ", "Hoshea", "Salvation"),
    "Joel": ("יוֹאֵל", "Yoel", "YHWH is God"),
    "Amos": ("עָמוֹס", "Amos", "Burden-bearer"),
    "Obadiah": ("עֹבַדְיָה", "Ovadyah", "Servant of YHWH"),
    "Jonah": ("יוֹנָה", "Yonah", "Dove"),
    "Micah": ("מִיכָה", "Mikhah", "Who is like YHWH?"),
    "Nahum": ("נַחוּם", "Nachum", "Comfort"),
    "Habakkuk": ("חֲבַקּוּק", "Chavaquq", "Embrace"),
    "Zephaniah": ("צְפַנְיָה", "Tsefanyah", "YHWH has hidden/treasured"),
    "Haggai": ("חַגַּי", "Chaggai", "Festive"),
    "Zechariah": ("זְכַרְיָה", "Zekharyah", "YHWH remembers"),
    "Malachi": ("מַלְאָכִי", "Malakhi", "My messenger"),
    # ---- NT (common modern-Hebrew names) ----
    "Matthew": ("מַתִּתְיָהוּ", "Mattityahu", "Gift of YHWH"),
    "Mark": ("מַרְקוֹס", "Marqos", "Mark"),
    "Luke": ("לוּקָס", "Luqas", "Luke"),
    "John": ("יוֹחָנָן", "Yochanan", "YHWH is gracious"),
    "Acts": ("מַעֲשֵׂי הַשְּׁלִיחִים", "Ma'asei HaShlichim", "Acts of the Apostles"),
    "Romans": ("הָרוֹמִיִּים", "HaRomiyim", "The Romans"),
    "1 Corinthians": ("קוֹרִנְתִּיִּים", "Qorintiyim", "Corinthians"),
    "2 Corinthians": ("קוֹרִנְתִּיִּים", "Qorintiyim", "Corinthians"),
    "Galatians": ("הַגָּלָטִיִּים", "HaGalatiyim", "The Galatians"),
    "Ephesians": ("הָאֶפְסִיִּים", "HaEfesiyim", "The Ephesians"),
    "Philippians": ("הַפִּילִיפִּיִּים", "HaFilipiyim", "The Philippians"),
    "Colossians": ("הַקוֹלוֹסִיִּים", "HaQolosiyim", "The Colossians"),
    "1 Thessalonians": ("הַתְּסָלוֹנִיקִיִּים", "HaTesaloniqiyim", "The Thessalonians"),
    "2 Thessalonians": ("הַתְּסָלוֹנִיקִיִּים", "HaTesaloniqiyim", "The Thessalonians"),
    "1 Timothy": ("טִימוֹתִיאוֹס", "Timotios", "Honoring God"),
    "2 Timothy": ("טִימוֹתִיאוֹס", "Timotios", "Honoring God"),
    "Titus": ("טִיטוֹס", "Titos", "Titus"),
    "Philemon": ("פִילֵימוֹן", "Filemon", "Affectionate"),
    "Hebrews": ("הָעִבְרִיִּים", "HaIvrim", "The Hebrews"),
    "James": ("יַעֲקֹב", "Ya'aqov", "Jacob / holds the heel"),
    "1 Peter": ("כֵּיפָא", "Kefa", "Rock (Peter)"),
    "2 Peter": ("כֵּיפָא", "Kefa", "Rock (Peter)"),
    "1 John": ("יוֹחָנָן", "Yochanan", "YHWH is gracious"),
    "2 John": ("יוֹחָנָן", "Yochanan", "YHWH is gracious"),
    "3 John": ("יוֹחָנָן", "Yochanan", "YHWH is gracious"),
    "Jude": ("יְהוּדָה", "Yehudah", "Praise"),
    "Revelation": ("הִתְגַּלּוּת", "Hitgalut", "Unveiling / revelation"),
}
